FROM ubuntu:bionic

RUN apt-get update \
  && apt-get install -y \
  bind9 \
  bind9utils \
  dnsutils \
  bind9-doc

 COPY ./bind/named.conf.options /etc/bind/named.conf.options
 COPY ./bind/named.conf.local /etc/bind/named.conf.local
 COPY ./bind/zona1.dir /etc/bind/zona1.dir
 COPY ./bind/zona1.inv /etc/bind/zona1.inv


RUN sed -i 's/OPTIONS=.*/OPTIONS="-4 -u bind"/' /etc/default/bind9


# Run eternal loop
CMD ["/bin/bash", "-c", "while :; do sleep 10; done"]
